#include <gwion_util.h>
#include <gwion_ast.h>
#include <gwfmt.h>

ANN static void gwfmt_symbol(Gwfmt *a, const Symbol b);
ANN static void gwfmt_array_sub(Gwfmt *a, const Array_Sub b);
ANN static void gwfmt_taglist(Gwfmt *a, const TagList *b);
ANN static void gwfmt_tmplarg_list(Gwfmt *a, const TmplArgList *b);
ANN static void gwfmt_tmpl(Gwfmt *a, const Tmpl *b);
ANN static void gwfmt_range(Gwfmt *a, const Range *b);
ANN static void gwfmt_prim_id(Gwfmt *a, const Symbol *b);
ANN static void gwfmt_prim_num(Gwfmt *a, const struct gwint *b);
ANN static void gwfmt_prim_float(Gwfmt *a, const m_float *b);
ANN static void gwfmt_prim_str(Gwfmt *a, const struct AstString *b);
ANN static void gwfmt_prim_array(Gwfmt *a, const Array_Sub *b);
ANN static void gwfmt_prim_range(Gwfmt *a, const Range **b);
ANN static void gwfmt_prim_hack(Gwfmt *a, const Exp* *b);
ANN static void gwfmt_prim_interp(Gwfmt *a, const Exp* *b);
ANN static void gwfmt_prim_char(Gwfmt *a, const m_str *b);
ANN static void gwfmt_prim_nil(Gwfmt *a, const void *b);
ANN static void gwfmt_prim(Gwfmt *a, const Exp_Primary *b);
ANN static void gwfmt_var_decl(Gwfmt *a, const Var_Decl *b);
ANN static void gwfmt_exp_decl(Gwfmt *a, const Exp_Decl *b);
ANN static void gwfmt_exp_binary(Gwfmt *a, const Exp_Binary *b);
ANN static void gwfmt_exp_unary(Gwfmt *a, const Exp_Unary *b);
ANN static void gwfmt_exp_cast(Gwfmt *a, const Exp_Cast *b);
ANN static void gwfmt_exp_post(Gwfmt *a, const Exp_Postfix *b);
ANN static void gwfmt_exp_call(Gwfmt *a, const Exp_Call *b);
ANN static void gwfmt_exp_array(Gwfmt *a, const Exp_Array *b);
ANN static void gwfmt_exp_slice(Gwfmt *a, const Exp_Slice *b);
ANN static void gwfmt_exp_if(Gwfmt *a, const Exp_If *b);
ANN static void gwfmt_exp_dot(Gwfmt *a, const Exp_Dot *b);
ANN static void gwfmt_exp_lambda(Gwfmt *a, const Exp_Lambda *b);
ANN static void gwfmt_stmt_exp(Gwfmt *a, const Stmt_Exp b);
ANN static void gwfmt_stmt_while(Gwfmt *a, const Stmt_Flow b);
ANN static void gwfmt_stmt_until(Gwfmt *a, const Stmt_Flow b);
ANN static void gwfmt_stmt_for(Gwfmt *a, const Stmt_For b);
ANN static void gwfmt_stmt_each(Gwfmt *a, const Stmt_Each b);
ANN static void gwfmt_stmt_loop(Gwfmt *a, const Stmt_Loop b);
ANN static void gwfmt_stmt_if(Gwfmt *a, const Stmt_If b);
ANN static void gwfmt_stmt_code(Gwfmt *a, const Stmt_Code b);
ANN static void gwfmt_stmt_break(Gwfmt *a, const Stmt_Index b);
ANN static void gwfmt_stmt_continue(Gwfmt *a, const Stmt_Index b);
ANN static void gwfmt_stmt_return(Gwfmt *a, const Stmt_Exp b);
ANN static void gwfmt_case_list(Gwfmt *a, const StmtList *b);
ANN static void gwfmt_stmt_match(Gwfmt *a, const struct Match *b);
ANN static void gwfmt_stmt_case(Gwfmt *a, const struct Match *b);
ANN static void gwfmt_stmt_pp(Gwfmt *a, const Stmt_PP b);
ANN static void gwfmt_stmt_defer(Gwfmt *a, const Stmt_Defer b);
ANN static void gwfmt_stmt(Gwfmt *a, const Stmt* b);
ANN /*static */void gwfmt_arg_list(Gwfmt *a, const ArgList *b, const bool);
ANN static void gwfmt_variable_list(Gwfmt *a, const VariableList *b);
ANN static void gwfmt_stmt_list(Gwfmt *a, const StmtList *b);
ANN static void gwfmt_func_base(Gwfmt *a, const Func_Base *b);
ANN static void gwfmt_section(Gwfmt *a, const Section *b);
