name: C/C++ CI

on:
  [push, workflow_dispatch, repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Gwion
      run: |
        git clone https://github.com/Gwion/Gwion
        cd Gwion
        git submodule update --init
        make
        
    - name: make
      run: CFLAGS="-IGwion/include -IGwion/ast/include -IGwion/util/include -LGwion -LGwion/ast -LGwion/util" make
