name: C/C++ CI

on:
  [push, workflow_dispatch, repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Gwion
      run: |
        git clone https://github.com/Gwion/Gwion
        cd Gwion
        git submodule update --init util ast libcmdapp
        cd util; git submodule update --init; cd ..
        cd ast; git submodule update --init; cd ..
        make
        
    - name: make
      run: CFLAGS="-IGwion/include -IGwion/ast/include -IGwion/ast/libprettyerr/src -IGwion/util/libtermcolor/src -IGwion/util/include -LGwion -LGwion/ast -LGwion/util -LGwion/ast/libprettyerr -LGwion/util/libtermcolor" make
